
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/demo
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver

# MariaDB 사용시
#  datasource:
#    url: jdbc:mariadb://yukmaro.cafe24.com/yukmaro
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: yukmaro
#    password: yukmaro99

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true

  profiles:
    include: oauth